image: python:3.7-alpine

stages:
  - doc_test
  - doc_deploy
  - build_debug
  - build_release

variables:
  GIT_SUBMODULE_STRATEGY: recursive

release_project:
  stage: build_release
  before_script:
  - "pip install -U platformio"
  script: "platformio run -e Release"

debug_project:
  stage: build_debug
  before_script:
  - "pip install -U platformio"
  script: "platformio run -e Debug"

doc_test:
  stage: doc_test
  script:
  - pip install -U sphinx
  - pip install sphinx-rtd-theme
  - sphinx-build -b html . public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    
pages:
  stage: doc_deploy
  script:
  - pip install -U sphinx
  - pip install sphinx-rtd-theme
  - sphinx-build -b html . public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH