stages:
  - build_debug
  - build_release

variables:
  GIT_SUBMODULE_STRATEGY: recursive

release_project:
  stage: build_release
  image: python:2.7
  before_script:
  - "pip install -U platformio"
  script: "platformio run -e Release"

debug_project:
  stage: build_debug
  image: python:2.7
  before_script:
  - "pip install -U platformio"
  script: "platformio run -e Debug"